import { Header } from "@/components/shared/header";
import type { Metadata } from "next";
// import "../globals.css"; можно сделать отдельный если нужен и будет свой стиль

export const metadata: Metadata = {
  // название и описание для сео
  title: "Next Pizza | Главная",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen">
      <Header />
      {children}
    </main>
  );
}
